version: "3.9"

networks:
  nw-db:
    driver: bridge

services:
  backend:
    container_name: backend

    build:
      context: ./backend
      dockerfile: ./Dockerfile

    restart: always

    volumes:
      - type: bind
        source: ./backend
        target: /data

    ports:
      - "4000:4000"

    networks:
      nw-db: {}

    env_file:
      - ./config/.env

  frontend:
    container_name: frontend

    build:
      context: ./frontend
      dockerfile: ./Dockerfile

    restart: always

    volumes:
      - type: bind
        source: ./frontend
        target: /data

    ports:
      - "3000:3000"

    env_file:
      - ./config/.env

  postgres:
    container_name: postgres

    image: postgres:latest

    volumes:
      - type: bind
        source: ./db
        target: /var/lib/postgresql/data/pgdata

    restart: always

    ports:
      - 5432

    networks:
      nw-db:
        aliases:
          - postgres

    env_file:
      - ./config/.env

  pgadmin:
    container_name: pgadmin

    image: dpage/pgadmin4:latest

    restart: always

    ports:
      - "80:80"

    env_file:
      - ./config/.env

    networks:
      nw-db: {}
# volumes:
#   v_react:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: $PWD/srcs/react/

