db:
  host: "localhost"
  username: "postgres"
  password: "4242"
  synchronize: true

jwt:
  secret: "dev-test"

intra:
  client_id: "u-s4t2ud-d66732cf3b341b21ff4c3596d13133df0c2365a3c855440ea26cb9b60f52c668"
  client_secret: "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"
  redirect_uri: "http://localhost:4000/auth/login/"
  url: "https://api.intra.42.fr/oauth/token"
